<?php
// Find Laravel root via artisan
$dirs = glob('/home/ceylonar/*/artisan') ?: glob('/home/*/artisan') ?: [];
if(!$dirs){ echo "artisan not found"; exit; }
$root = dirname($dirs[0]);

// Parse .env for DB credentials
$env = [];
foreach(file($root.'/.env') as $line){
    $line = trim($line);
    if(!$line || $line[0]==='#' || !str_contains($line,'=')) continue;
    [$k,$v] = explode('=', $line, 2);
    $v = trim($v,"\"' \t");
    $env[trim($k)] = $v;
}
$host = $env['DB_HOST'] ?? '127.0.0.1';
$port = $env['DB_PORT'] ?? '3306';
$db   = $env['DB_DATABASE'] ?? '';
$user = $env['DB_USERNAME'] ?? '';
$pass = $env['DB_PASSWORD'] ?? '';

try {
    $pdo = new PDO("mysql:host=$host;port=$port;dbname=$db;charset=utf8mb4", $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(Exception $e){ echo "DB error: ".$e->getMessage(); @unlink(__FILE__); exit; }

$posts = [
 ['How to Import Ceylon Cinnamon: Grades, Regulations & MOQ Guide','how-to-import-ceylon-cinnamon-guide','Import Guides','Everything wholesale buyers need to know before sourcing Ceylon true cinnamon — grades, EU MRL compliance, minimum order quantities and documentation.','<p>Ceylon cinnamon (<em>Cinnamomum verum</em>) is the world\'s only true cinnamon, grown almost exclusively in Sri Lanka.</p><h2>Ceylon Cinnamon Grades</h2><ul><li><strong>Alba (00000):</strong> Finest grade, quill &lt;6 mm. Premium pricing for gourmet and pharmaceutical buyers.</li><li><strong>Continental (000):</strong> 6–10 mm. Most widely exported — excellent quality/price balance.</li><li><strong>Mexican (0–1):</strong> 10–16 mm. Value-grade for food manufacturing and extraction.</li></ul><h2>EU Regulatory Requirements</h2><p>Ceylon cinnamon coumarin content is naturally very low (avg 0.017 g/kg) — far below EU alert levels — giving it a significant regulatory advantage over cassia.</p><h2>Required Documentation</h2><ul><li>Phytosanitary Certificate</li><li>Certificate of Origin</li><li>ISO 22000 / HACCP certificate</li><li>Heavy metal and pesticide residue test report</li></ul><p>Ready to request a sample? <a href="/contact">Contact our export team</a>.</p>',date('Y-m-d H:i:s', strtotime('-3 days'))],
 ['Ceylon Tea Grades Explained: A Buyer\'s Guide for Importers','ceylon-tea-grades-importers-guide','Import Guides','OP, BOP, FBOP, BOPF — decoding Ceylon tea grading so you can specify the right grade for your market, from premium loose-leaf retail to tea bag manufacturing.','<p>Sri Lanka produces over 300 million kilograms of tea annually, exporting to more than 100 countries.</p><h2>Orthodox Whole-Leaf Grades</h2><ul><li><strong>OP (Orange Pekoe):</strong> Long, thin, tightly rolled leaves. Classic loose-leaf grade for premium retail.</li><li><strong>FOP (Flowery Orange Pekoe):</strong> Contains more golden tips. Lighter, more aromatic.</li><li><strong>GFOP (Golden Flowery Orange Pekoe):</strong> High proportion of golden tips. Top-tier retail and gifting.</li></ul><h2>Broken Grades</h2><ul><li><strong>BOP (Broken Orange Pekoe):</strong> Stronger, faster-brewing cup. Widely used in blending and retail teabags.</li><li><strong>BOPF (Broken Orange Pekoe Fannings):</strong> Optimised for envelope-style teabags. Most widely exported Ceylon grade globally.</li></ul><p>Ceylon Aroma sources across all elevations. <a href="/contact">Request a tasting sample</a>.</p>',date('Y-m-d H:i:s', strtotime('-6 days'))],
 ['ISO 22000 & HACCP Certification: What Spice Importers Need to Know','iso-22000-haccp-certification-spice-importers','Quality & Compliance','Understanding food safety certifications is non-negotiable for spice importers. Here\'s what ISO 22000 and HACCP mean in practice.','<p>Food safety compliance is the single biggest due-diligence task when selecting a spice exporter.</p><h2>What is HACCP?</h2><p>Hazard Analysis and Critical Control Points (HACCP) is a preventive food safety system. It is a regulatory requirement in the EU and US for food manufacturers.</p><h2>What is ISO 22000?</h2><p>ISO 22000:2018 is an international standard that integrates HACCP principles into a full food safety management system, audited by accredited third-party bodies.</p><h2>How to Verify Certificates</h2><ol><li>Ask for the full certificate (not just a logo).</li><li>Check the scope covers your products.</li><li>Verify the certificate is within its validity period.</li><li>Confirm the certifying body is IAF-accredited.</li></ol><p>Ceylon Aroma holds current ISO 22000 and HACCP certifications, available on request. <a href="/quality">View our quality page</a>.</p>',date('Y-m-d H:i:s', strtotime('-10 days'))],
 ['Shipping Spices from Sri Lanka: Incoterms, Freight & Lead Times','shipping-spices-sri-lanka-incoterms-freight-guide','Export Logistics','FOB, CIF, DAP — which Incoterm is right for your spice import? A practical guide to freight options, lead times and cost considerations.','<p>Getting the logistics right is just as important as product quality when importing spices from Sri Lanka.</p><h2>Choosing the Right Incoterm</h2><p><strong>FOB Colombo</strong> is the most common term for experienced importers. Risk transfers when goods cross the ship\'s rail. <strong>CIF</strong> means the exporter arranges freight and marine insurance. <strong>DAP</strong> is door-to-door.</p><h2>Sea Freight Lead Times</h2><ul><li>Europe: 18–24 days</li><li>USA East Coast: 22–28 days</li><li>Middle East: 7–12 days</li><li>Australia: 14–18 days</li></ul><h2>LCL vs FCL</h2><p>Less-than-container-load (LCL) suits orders under 5–8 CBM. A full 20-foot container (FCL) offers 20–35% cost saving per kg. <a href="/contact">Get a freight quote</a>.</p>',date('Y-m-d H:i:s', strtotime('-14 days'))],
 ['Private Label Spices from Sri Lanka: How the Process Works','private-label-spices-sri-lanka-process','Private Label','Thinking of launching your own spice brand with Ceylon origin products? Here\'s the step-by-step process — from brand brief to container on your dock.','<p>Private label sourcing from Sri Lanka has become one of the fastest-growing segments of the global spice trade.</p><h2>The Step-by-Step Process</h2><ol><li><strong>Brand Brief:</strong> Share your target market, positioning, pack sizes and regulatory requirements.</li><li><strong>Product Specification:</strong> We agree the grade, moisture, particle size, colour value.</li><li><strong>Sample Approval:</strong> We produce a reference sample to specification. Typically 1–2 rounds.</li><li><strong>Artwork &amp; Packaging:</strong> Your design team provides print-ready artwork.</li><li><strong>Production &amp; QC:</strong> Third-party lab testing on the production batch before packing.</li><li><strong>Packing &amp; Export:</strong> Products packed under your brand with full export documentation.</li></ol><p>MOQs: 500 units for retail pouches, 100 kg net for bulk bags. <a href="/contact">Start your brief</a>.</p>',date('Y-m-d H:i:s', strtotime('-18 days'))],
 ['Ceylon Black Pepper vs Indian Pepper: A Buyer\'s Comparison','ceylon-black-pepper-vs-indian-pepper-buyers-guide','Product Guides','How does Sri Lankan black pepper stack up against Malabar and Tellicherry from India? A practical flavour, quality and price comparison for wholesale buyers.','<p>Black pepper is the world\'s most traded spice, and Sri Lanka competes directly with India\'s Malabar and Tellicherry origins.</p><h2>Flavour Profile</h2><p><strong>Ceylon pepper</strong> (Kandy and Matale regions) delivers a clean, bright heat with floral-citrus aromatic notes. Its volatile oil content (3.5–5%) gives an immediate, punchy aroma valued by premium spice brands. <strong>Malabar pepper</strong> is earthier and more resinous — ideal for industrial applications. <strong>Tellicherry</strong> (size-graded 4.25mm+) is the premium Indian origin with greater aroma complexity.</p><h2>Which to Choose?</h2><p>For premium retail where origin story matters — Ceylon. For cost-effective industrial use — Malabar. <a href="/contact">Request a sample</a>.</p>',date('Y-m-d H:i:s', strtotime('-22 days'))],
 ['Ceylon Coffee for Private Label: Sourcing Specialty Beans from Sri Lanka','ceylon-coffee-private-label-sourcing-guide','Product Guides','Sri Lanka\'s single-origin Arabica and Robusta coffees are gaining ground in specialty markets. What importers and private label brands need to know.','<p>Ceylon coffee has a storied history — Sri Lanka was once the world\'s largest coffee exporter before the 1869 coffee leaf rust devastated plantations. Today, high-elevation Arabica from Kandy, Nuwara Eliya and Badulla is reclaiming its place in specialty coffee circles.</p><h2>Ceylon Coffee Character</h2><p>High-grown Ceylon Arabica (1,000–1,500m) produces a medium-bodied cup with mild acidity, subtle chocolate and dried-fruit notes, and a clean finish. Robusta from the low-country is bold and full-bodied — ideal for espresso blending and instant coffee manufacturing.</p><h2>Private Label Options</h2><p>We supply green bean and roasted whole bean, ground to specification. Options include branded retail bags (100g–1kg), capsule filling, and bulk green bean. Minimum order: 50 kg for roasted private label. <a href="/contact">Start a conversation</a>.</p>',date('Y-m-d H:i:s', strtotime('-26 days'))],
];

$stmt = $pdo->prepare("SELECT COUNT(*) FROM blog_posts WHERE slug=?");
$ins  = $pdo->prepare("INSERT INTO blog_posts (title,slug,category,excerpt,content,published_at,status,created_at,updated_at) VALUES (?,?,?,?,?,?,1,NOW(),NOW())");
$n = 0;
foreach($posts as $p){
    $stmt->execute([$p[1]]);
    if($stmt->fetchColumn() == 0){
        $ins->execute([$p[0],$p[1],$p[2],$p[3],$p[4],$p[5]]);
        $n++;
    }
}
$total = $pdo->query("SELECT COUNT(*) FROM blog_posts")->fetchColumn();
echo "Inserted $n posts. Total in DB: $total";
@unlink(__FILE__);
